apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: gentry
build:
  local:
    useBuildkit: true
  artifacts:
  - image: gentry
    context: .
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
    - kubernetes/template.compiled.yaml
