apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwsgi
spec:
  selector:
    matchLabels:
      stack: !Var djangoapp_name
      component: uwsgi
  template:
    metadata:
      labels:
        stack: !Var djangoapp_name
        component: uwsgi
    spec:
      enableServiceLinks: false
      securityContext: !Var uwsgi_pod_security_context
      initContainers:
        - !If
            test: !Var setup_should_run
            then:
              name: setup
              image: !Var djangoapp_image
              args: ["python", "manage.py", "migrate"]
              env: !Var uwsgi_environment
              securityContext: !Var uwsgi_container_security_context
      containers:
        - name: uwsgi
          image: !Var djangoapp_image
          ports:
            - containerPort: 8000
          env: !Var uwsgi_environment
          securityContext: !Var uwsgi_container_security_context
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            periodSeconds: 30
          volumeMounts:
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
