apiVersion: v1
kind: Service
metadata:
  name: uwsgi
  labels:
    stack: !Var djangoapp_name
    component: djangoapp
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    stack: !Var djangoapp_name
    component: uwsgi
